### ISSUE TITLE
Improved search function

### ISSUE THREAD

**Issue by czavoianu** [fredmorcos/tvrank#1]
The search function should allow for partial and/or incomplete matches. For example:
 - a search for "the a team" should yield "The A-Team" 2010 movie or the 1983 series "The A-Team"
 - a search for "equilib" should identify at least two movies titled "Equilibrium" (from 2002 and 2017)
 - ideally, the "strength" of the match should be customisable via flags (-e exact/strong, -d default, -t tentative/weak)

**Comment by fredmorcos** [comment]
Thanks!

I think there are two separate issues at play here, so I went ahead and created the following tickets:
* https://github.com/fredmorcos/tvrank/issues/3
* https://github.com/fredmorcos/tvrank/issues/4

And I created the following milestone to track them: https://github.com/fredmorcos/tvrank/milestone/1

**Comment by fredmorcos** [comment]
An option for exact matching will be available in 0.7.0. This effectively provides flexible searching. The updated README contains more information and examples on how to make use of it.
