### ISSUE TITLE
TVrank should respect the `NO_COLOR` environment variable

### ISSUE THREAD

**Issue by fredmorcos** [fredmorcos/tvrank#14]
When the `NO_COLOR` environment variable is set, TVrank should refrain from displaying colors (and perhaps even displaying unicode art for tables).

See https://no-color.org/ for more information.

Additionally, a command-line parameter (e.g. `--color`) should be added to override the `NO_COLOR` environment variable.

Ideally, `--color` should take one of the following values:
* `on` (the default) means that color and unicode art is output only when `stdout` is a terminal.
* `off` means to never output color and unicode art.
* `always` means to always output color and unicode art even when `stdout` is not a terminal.

**Comment by caglaryucekaya** [comment]
Can I take this one too :smile:

**Comment by fredmorcos** [comment]
Yes of course 😃 I think it might make sense to split it into a couple of separate issues and have an overall milestone. However you'd like to do it though it's up to you.

**Comment by fredmorcos** [comment]
As a first step, I think you need to handle two things:

1. Is the `NO_COLOR` environment variable set?
2. Is the `--color` command-line argument passed? (You will need to add support for the `--color` argument)

The latter takes precedence. Examples:

- If `NO_COLOR` is not set, and `--color` is not passed, then still show colors (the default).
- If `NO_COLOR` is set but `--color` is passed, then still show colors.
- If `NO_COLOR` is set and `--color` is not passed, then don't show colors.

The places where colors are displayed are the Rating column as you mentioned, and also the column titles that are displayed in bold (I guess this can also be considered coloring) under `search::create_table()`:

```rust
  table.add_row(Row::new(vec![
    Cell::new("Primary Title").with_style(Attr::Bold),
    Cell::new("Original Title").with_style(Attr::Bold),
    Cell::new("Year").with_style(Attr::Bold),
    Cell::new("Rating").with_style(Attr::Bold),
    Cell::new("Votes").with_style(Attr::Bold),
    Cell::new("Runtime").with_style(Attr::Bold),
    Cell::new("Genres").with_style(Attr::Bold),
    Cell::new("Type").with_style(Attr::Bold),
    Cell::new("IMDB ID").with_style(Attr::Bold),
    Cell::new("IMDB Link").with_style(Attr::Bold),
  ]));
```
