### ISSUE TITLE
Support JSON output

### ISSUE THREAD

**Issue by fredmorcos** [fredmorcos/tvrank#17]
Support results output in JSON format, as an example:

```json
{
  "movies": [
    ...
  ],
  "series": [
    ...
  ]
}
```

**Comment by Olsi-B** [comment]
@fredmorcos If the ticket is not assigned yet, I'd like to work on it.

**Comment by fredmorcos** [comment]
Awesome, go for it!

**Comment by Olsi-B** [comment]
#35 can be reviewed.
I also refactored some code, mostly to separate responsibilities. This should make it easier to implement the `YAML` format ticket.

One other thing. When running `clippy` locally I don't get all the errors. What version is running on the pipeline? Locally I'm running `0.1.58`.

**Comment by fredmorcos** [comment]
We can close this now thanks to your contribution in #35!
Btw, you can use something like "Closes #17" in the commit message to automatically close the related issue.
