### ISSUE TITLE
Support the display of only the top N results

### ISSUE THREAD

**Issue by fredmorcos** [fredmorcos/tvrank#19]
A command-line option like `--results 3` or `--top 3` could be used to only show the top 3 search results of movies and series.

**Comment by caglaryucekaya** [comment]
Hi I'd like to work on this!

**Comment by fredmorcos** [comment]
Awesome! Go ahead 😃 If you need any help just let me know

**Comment by fredmorcos** [comment]
There was an oversight on my part on PR #22, I would prefer if the `top` value would be an `Option<usize>` instead of `Option<u16>`. I'm fixing that in PR #23, I hope you don't mind?

**Comment by caglaryucekaya** [comment]
Yeah of course. It's used as usize in the end, so it's better to define it as usize from the beginning.
