### ISSUE TITLE
Move from `structopt` to `clap`

### ISSUE THREAD

**Issue by fredmorcos** [fredmorcos/tvrank#41]
`structopt` is now in maintenance mode and `TVrank` should move to `clap` instead which has incorporated almost all of `structopt`'s features.

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.

https://docs.rs/structopt/latest/structopt/

**Comment by oylenshpeegul** [comment]
I think I can try this. I have played with clap 3 a couple of times (only once with subcommands).

**Comment by fredmorcos** [comment]
Alright, I'll be finishing up a large refactoring of some related part of the code in `main.rs` by tomorrow perhaps. Then, on Wednesday there's a group programming session working on #28. So you have some options on when to approach this:

1. If you're comfortable with rebasing and dealing with merge conflicts, you can get started on this now.
2. If not, you can wait until I merge my changes, but that means you should be done with integrating clap before Wednesday.
3. Wait until after the session on Wednesday.

**Comment by oylenshpeegul** [comment]
Hrm. [I think I've finished against the current main.rs](https://github.com/oylenshpeegul/tvrank), but rebasing and dealing with merge conflicts sounds like a pain. Perhaps I'll just re-do it after you've merged.

**Comment by fredmorcos** [comment]
Oh in this case just open a PR then! I'll deal with the rebase and merge conflicts.
