### ISSUE TITLE
Searching for "the weather man" or "the godfather" reveals no results

### ISSUE THREAD

**Issue by fredmorcos** [fredmorcos/tvrank#49]
As the title says. Searching for "weather man" works fine and shows titles called "The Weather Man", but searching for "the weather man" reveals no series and movies matches:

```
>  tvrank title "the weather man"
No movie matches found for `weather, the, man`
No series matches found for `weather, the, man`
Total time: 399ms 941us 178ns
```

```
>  tvrank title "the weatherman"
No movie matches found for `the, weatherman`
No series matches found for `the, weatherman`
Total time: 396ms 281us 867ns
```

It also doesn't seem to be the "the" in the search keywords causing the problem:

```
tvrank title "amazing spider man"
Found 30 movie matches for `spider, amazing, man`:
...
Found 2 series matches for `spider, amazing, man`:
```

```
tvrank title "the amazing spider man"
Found 27 movie matches for `amazing, the, man, spider`:
...
Found 1 series match for `amazing, the, man, spider`:
```

**Comment by koushik-ms** [comment]
is it the lack of space between weather and man ? (e.g., "the weather man" vs "the weatherman")

**Comment by fredmorcos** [comment]
> is it the lack of space between the words "weather" and "man" ? (e.g., "the weather man" vs "the weatherman")

I'm not sure. The first two examples show both not returning any results.

**Comment by koushik-ms** [comment]
you are right. it's 100% reproducible. also for batman.
I couldn't help but noticing the word weather contains the word "the".

**Comment by koushik-ms** [comment]
the same behavior when searching for "The Godfather"

```
gitpod /workspace/tvrank (main) $ cargo run --release -- title "godfather"
...
Found 136 movie matches for `godfather`:
...
Found 11 series matches for `godfather`:

Total time: 782ms 976us 53ns
gitpod /workspace/tvrank (main) $ cargo run --release -- title "the godfather"
    Finished release [optimized + debuginfo] target(s) in 0.08s
     Running `target/release/tvrank title 'the godfather'`
No movie matches found for `the, godfather`
No series matches found for `the, godfather`
Total time: 809ms 469us 815ns
```

**Comment by fredmorcos** [comment]
> I couldn't help but noticing the word weather contains the word "the".

Good catch!

> the same behavior when searching for "The Godfather"

Then yeah, it's probably the "the". I'll work on debugging it this evening or perhaps tomorrow. Unless you want to do it?
